import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { getIDs } from '../utils/getRandomNPC'

const Home: NextPage = () => {

  const [first, second] = getIDs();

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className='w-screen h-screen antialiased bg-slate-800 flex flex-col items-center'>
        <h1 className='text-3xl text-slate-50'>
          Which NPC is cooler?
        </h1>
        <div className='p-32'></div>
        <div className='border rounded p-8 flex flex-row items-center justify-between max-w-2xl'>
          <div className='w-32 h-32 border rounded' suppressHydrationWarning>{first}</div>

          <div className='text-slate-50 text-xl'>Vs</div>

          <div className='w-32 h-32 border rounded ' suppressHydrationWarning>{second}</div>

        </div>
      </div>

    </div>
  )
}

export default Home
