import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className='w-screen h-screen antialiased bg-slate-800'>
        <h1 className='text-3xl text-slate-50'>
          Which NPC is cooler?
        </h1>
        <div className='border rounded p-8 flex flex-row items-center justify-around'>
          <div className='w-32 h-32 border rounded'></div>

          <div className='text-slate-50 text-xl'>Vs</div>

          <div className='w-32 h-32 border rounded'></div>

        </div>
      </div>

    </div>
  )
}

export default Home
